"""License key system for AirNode.

AirNode is open-source (MIT), but a lightweight license gate is useful for
a commercial distribution. This module provides:

- A 14-day trial that starts on first launch.
- Product-key validation using an HMAC-SHA256 signature so keys can be
  generated offline by the developer without a server round-trip.
- Persistent license state stored in the data directory.

Key format (generated by the developer with ``generate_key``):
    ABNODE-XXXXX-XXXXX-XXXXX-XXXXX

The trial is intentionally lenient: it is a display/tracked state, not a
DRM wall. Anyone with the MIT source can remove it; this exists so the
desktop app can show "Trial — buy a license" messaging to drive
conversions.
"""

import hashlib
import hmac
import json
import secrets
import string
import threading
import time
from dataclasses import dataclass
from pathlib import Path

from logging_config import get_logger
from paths import get_data_dir


logger = get_logger(__name__)

# ── Configuration ──────────────────────────────────────────────────────
# Secret used to sign/verify product keys. In a real deployment this would
# be different per build. The value here is a placeholder — replace it and
# regenerate all keys if you distribute builds publicly.
LICENSE_SECRET = b"AirNode-4f9a2c1e-b7d3-4a61-9e8f-2c0d5a6b7c8d"

TRIAL_DAYS = 14
LICENSE_FILE = get_data_dir() / ".airnode-license.json"

_lock = threading.Lock()


@dataclass
class LicenseState:
    """Persisted license state."""
    activated: bool = False
    license_key: str = ""
    license_type: str = ""       # "full" or "trial"
    activated_at: float = 0.0
    trial_started_at: float = 0.0
    # Holds the trial expiry; recomputed on read so users can't just edit the json
    trial_expires_at: float = 0.0


def _read_state() -> LicenseState:
    """Load license state from disk, falling back to defaults."""
    try:
        if LICENSE_FILE.exists():
            with LICENSE_FILE.open("r", encoding="utf-8") as f:
                data = json.load(f)
            return LicenseState(**data)
    except Exception:
        pass
    return LicenseState()


def _write_state(state: LicenseState) -> None:
    """Persist license state to disk."""
    try:
        with _lock:
            with LICENSE_FILE.open("w", encoding="utf-8") as f:
                json.dump(state.__dict__, f, indent=2)
    except OSError as e:
        logger.warning("Failed to save license state: %s", e)


def _normalize_key(key: str) -> str:
    """Strip separators/spaces and uppercase a raw key."""
    cleaned = "".join(ch for ch in key.strip().upper() if ch.isalnum())
    # Format as ABNODE-XXXXX-XXXXX-XXXXX-XXXXX
    if len(cleaned) >= 6 and cleaned.startswith("ABNODE"):
        body = cleaned[6:]
        groups = [body[i:i + 5] for i in range(0, min(len(body), 20), 5)]
        return "ABNODE-" + "-".join(groups)
    return cleaned


def _sign(payload: str) -> str:
    """HMAC-SHA256 signature of the payload, truncated to 4 chars per 5-char group."""
    full = hmac.new(LICENSE_SECRET, payload.encode("utf-8"), hashlib.sha256).hexdigest()
    # Take 16 hex chars -> 4 groups of 4, encoded as base32-like chars
    return full[:16].upper()


def _valid_key_shape(key: str) -> bool:
    """Check the key matches ABNODE-XXXXX-XXXXX-XXXXX-XXXXX."""
    parts = key.split("-")
    return (
        len(parts) == 5
        and parts[0] == "ABNODE"
        and all(len(p) == 5 and p.isalnum() for p in parts[1:])
    )


def generate_key() -> str:
    """Generate a new product key (for the developer / sales).

    Keys are signed with the shared secret, so they can be verified
    offline by any build that knows the secret.
    """
    alphabet = string.ascii_uppercase + string.digits
    # 3 random groups + 1 signature group = 20 chars of payload
    payload = "".join(secrets.choice(alphabet) for _ in range(15))
    sig = _sign(payload)[:5]
    key = f"ABNODE-{payload[0:5]}-{payload[5:10]}-{payload[10:15]}-{sig}"
    return key


def validate_key(key: str) -> bool:
    """Validate a product key offline using HMAC."""
    normalized = _normalize_key(key)
    if not _valid_key_shape(normalized):
        return False
    _, p1, p2, p3, sig = normalized.split("-")
    payload = p1 + p2 + p3
    expected = _sign(payload)[:5]
    return hmac.compare_digest(sig, expected)


def get_license_status() -> dict:
    """Return the current license status for the UI.

    - If activated with a valid key -> status "active"
    - Otherwise -> status "trial" with days remaining (or "expired")
    """
    state = _read_state()
    now = time.time()

    # If a key is stored but invalid (secret changed / tampered), downgrade to trial
    if state.activated and state.license_key:
        if not validate_key(state.license_key):
            logger.warning("Stored license key is no longer valid — falling back to trial")
            state = LicenseState()
            _write_state(state)

    if state.activated and state.license_key and validate_key(state.license_key):
        return {
            "status": "active",
            "license_type": "full",
            "license_key": state.license_key,
            "activated_at": state.activated_at,
        }

    # Trial mode
    trial_started = state.trial_started_at or state.activated_at or now
    if not state.trial_started_at:
        state.trial_started_at = trial_started
        _write_state(state)

    expires = trial_started + TRIAL_DAYS * 24 * 60 * 60
    remaining = expires - now
    return {
        "status": "trial" if remaining > 0 else "expired",
        "license_type": "trial",
        "trial_days": TRIAL_DAYS,
        "trial_started_at": trial_started,
        "trial_expires_at": expires,
        "days_remaining": max(0, int(remaining // 86400)),
    }


def activate_key(key: str) -> tuple[bool, str, dict]:
    """Try to activate a license key. Returns (ok, message, status)."""
    normalized = _normalize_key(key)
    if not _valid_key_shape(normalized):
        return False, "Invalid key format. Expected ABNODE-XXXXX-XXXXX-XXXXX-XXXXX.", get_license_status()

    if not validate_key(normalized):
        return False, "That license key is not valid.", get_license_status()

    state = LicenseState(
        activated=True,
        license_key=normalized,
        license_type="full",
        activated_at=time.time(),
    )
    _write_state(state)
    return True, "License activated successfully. Thank you!", get_license_status()


def revoke_license() -> dict:
    """Remove the activated license, returning to trial mode."""
    state = LicenseState()
    _write_state(state)
    return get_license_status()


def reset_trial() -> None:
    """Reset the trial timer (developer/testing helper)."""
    state = LicenseState()
    state.trial_started_at = time.time()
    _write_state(state)